version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    image: typescript-express
    container_name: server
    environment:
      - DB_URL=mongodb://mongo:27017/blog
      - REDIS_URL=redis://redis:6379
      - ES_NODE=http://es:9200
      - INDEX_NAME=post
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - mongo
      - es
      - redis
    depends_on:
      - mongo
      - es
      - redis
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    networks:
      - backend
  es:
    build: ./es
    environment:
      - "discovery.type=single-node"
    ports:
      - '9200:9200'
    networks:
      - backend
  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - backend
  logstash:
    image: logstash-mongo
    volumes:
      - ./logstash/config:/usr/share/logstash/pipeline/
      - ./logstash/data:/opt/data
    networks:
      - backend
    links:
      - es

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
