@baseURL = http://localhost:3000

# Create Comment
POST {{ baseURL }}/posts/62fa428fe154ccc7e9cde2a2/comments
Content-Type: application/json

{
    "content": "112231212",
    "commentId":"62fa42bde154ccc7e9cde2d9"

}

###
# Get Comments
GET  {{ baseURL }}/posts/62fa428fe154ccc7e9cde2a2/comments