@baseURL = http://localhost:3000

###
# Login
POST {{ baseURL }}/login
Content-Type: application/json

{
    "email": "example@email.com",
    "password": "password"
}


###
# Create post
POST {{ baseURL }}/posts
Content-Type: application/json

{
    "title":"88888",
    "content": "中国人民大团结"
}

###
# Edit post
PUT {{ baseURL }}/posts
Content-Type: application/json

{
    "postId":"62f9b6d3602cce91c3abff9e",
    "title":"三民主义",
    "content": "民主，"
}

###
# PAGE post
POST {{ baseURL }}/posts/page
Content-Type: application/json

{
    "pageNum":1,
    "pageSize":2,
    "keyword":"中国人民"
}

###
#Get Post
GET {{ baseURL }}/posts/62f9b6d3602cce91c3abff9e