# baseURL
@baseURL = http://localhost:3000

###
# Find All Users
GET {{ baseURL }}/users



###
# Find User By Id
GET {{ baseURL }}/users/62f5c49cfff656b3d4ad7d45



###
# Create User
POST {{ baseURL }}/users
Content-Type: application/json

{
    "name":"tom1",
    "email": "example@email.com",
    "password": "password"
}

###
# Modify User By Id
PUT {{ baseURL }}/users/1
Content-Type: application/json

{
    "email": "example@email.com",
    "password": "password"
}

###
# Login
POST {{ baseURL }}/login
Content-Type: application/json

{
    "email": "example@email.com",
    "password": "password"
}


###
# Logout
POST {{ baseURL }}/logout



###
# Delete User By Id
DELETE {{ baseURL }}/users/62f5c49cfff656b3d4ad7d45



