# Common build stage
FROM logstash:7.17.5
RUN bin/logstash-plugin install logstash-input-mongodb
# RUN bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.17.5/elasticsearch-analysis-ik-7.17.5.zip  --batch